### ISSUE TITLE
INTERNAL_ERROR

### ISSUE THREAD

**Issue by medaamarnadh** [paypal/PayPal-node-SDK#102] opened 2015-07-30 05:52 UTC
Hi I am using 

Paypal-node-sdk in my node webapplication.

I am continously getting INTERNAL_ERROR with the method payout with my sandox environment.
But its working fine from last one month

My request body is 
{"sender_batch_header":{"sender_batch_id":"38xwjc3di","email_subject":"You have a payment","recipient_type":"EMAIL"},"items":[{"recipient_type":"EMAIL","amount":{"value":0.99,"currency":"USD"},"receiver":"amaranadh.meda-buyer@paradigmcreatives.com","note":"Thank you.","sender_item_id":"2565jhhjkhk1438234381969"},{"recipient_type":"EMAIL","amount":{"value":0.99,"currency":"USD"},"receiver":"ramya.buddi@paradigmcreatives.com","note":"Thank you.","sender_item_id":"item_11438234381970"}]}

The response i was getting is 

{"response":{"name":"INTERNAL_ERROR","message":"An internal service error has occurred.","debug_id":"1aaed0b455d4d","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_ERROR","httpStatusCode":500},"httpStatusCode":500}

It was giving the debug id:  1aaed0b455d4d

**Comment by jaypatel512** [comment] 2015-07-30 08:34
I am able to reproduce this issue. I have raised the issue internally, and would be letting you know as soon as the issue is resolved.

**Comment by medaamarnadh** [comment] 2015-07-30 08:39
Thank you for the response. I am waiting for you .

**Comment by medaamarnadh** [comment] 2015-07-30 12:30
Hi i am waiting for your repsone. Do you want any other details please mention in the comments.
I will respond to you

**Comment by juwlee** [comment] 2015-07-30 13:27
@medaamarnadh can you try again and see if it still persists?

**Comment by jaypatel512** [comment] 2015-07-30 17:05
Tried them locally, and was able to see the success. Closing the issue. Please re-open if issue still exists.

**Comment by medaamarnadh** [comment] 2015-07-30 17:10
Hi thank you for the response. I was getting the error still.

**Comment by jaypatel512** [comment] 2015-07-30 17:12
Re-opening, as you are still getting that error. Can you please pass the `debug_id` for the failed try.

**Comment by medaamarnadh** [comment] 2015-07-30 17:13
1aaed0b455d4d

**Comment by jaypatel512** [comment] 2015-07-30 17:20
I have asked the internal team to look at it. Here is the internal tracking code: SRE-32577

**Comment by medaamarnadh** [comment] 2015-07-30 17:23
Hey thank you for the response. Its working fine now. 
If i have any problem again i will get back to you . 
If you can tell me exact problem why it was not working that would be great . If there is any thing wrong from my side then i  will try do not repeat the problem again.

**Comment by jaypatel512** [comment] 2015-07-30 17:25
The issue we were seeing was internal. We had resolved the issue. I will close the issue now. There was nothing wrong from your end. It was just a minor migration issue internally.

**Closed by jaypatel512** 2015-07-30 17:25 UTC
Labels: api-bug, api-payouts

**Comment by medaamarnadh** [comment] 2015-07-30 17:43
Ok thank you
