### ISSUE TITLE
Web hook validation fails on first try persistently.

### ISSUE THREAD

**Issue by AlexCatch** [paypal/PayPal-node-SDK#147] opened 2016-04-10 13:57 UTC
When I receive a web hook from Paypal, I pass over the ID of the web hook event to my Paypal manager class which in turn calls `Paypal.notification.webhookEvent.get`.

The first time the web hook is received I consistently get the error `'{"name":"INVALID_RESOURCE_ID","details":[],"message":"Resource id is invalid"}'`

Because an error is thrown, I return a 503 and the web hook gets fired again within a few minutes and it successfully validates and returns the response.

Is there any reason why it would be throwing this error consistently on every first web hook event?

**Comment by juwlee** [comment] 2016-04-11 13:23
@AlexCatch Can you please share `debug_id` for the 503 error and the same value when the call works?

**Comment by bluk** [comment] 2016-04-11 15:19
@AlexCatch This is a known issue in the web hook system. The issue is that the notification dispatch is fired off as soon as possible but does not guarantee that the web hook can be looked up immediately. Internal bug is being tracked under `ON-57`.

**Comment by AlexCatch** [comment] 2016-04-12 18:46
@bluk Is there a way around this issue for the time being? Maybe using a different method?

**Comment by bluk** [comment] 2016-04-12 20:45
@AlexCatch The only way I know to avoid this delay currently is to queue up the webhook notifications in your code and wait a few seconds (~10 seconds but times can vary) before trying to get the webhook resource.

The other server side SDKs (except PHP) verify the payload signature as detailed in the [Event Security](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/?mark=webhook) section of the Webhook documentation. The reason why the node.js and PHP SDK do not is because there has not been a good set of built-in standard library methods to verify the signature in those two languages.

**Comment by bluk** [comment] 2016-10-28 21:03
This should be fixed with #203 which will be in the next release.

**Closed by bluk** 2016-10-28 21:03 UTC
Labels: api-bug, api-webhooks
