### ISSUE TITLE
Cannot assign to read only property 'httpStatusCode'...

### ISSUE THREAD

**Issue by gharlock** [paypal/PayPal-node-SDK#161] opened 2016-06-28 06:52 UTC
Hello, 
I'm using PayPal-node-SDK v1.6.8 and sometimes the "paypal.payment.create" method fails with:
- **uncaughtException: Cannot assign to read only property 'httpStatusCode' of...**

Here the stack:
```
{
	"date": "Tue Apr 05 2016 20:56:11 GMT+0200 (CEST)",
	"process": {
		"pid": 26929,
		"uid": 0,
		"gid": 0,
		"cwd": "/var/service/shop_radiotaxivenezia",
		"execPath": "/usr/local/bin/node",
		"version": "v5.7.0",
		"argv": ["/usr/local/bin/node",
		"/var/www/node/shop_radiotaxivenezia/app.js"],
		"memoryUsage": {
			"rss": 97259520,
			"heapTotal": 66272744,
			"heapUsed": 47313016
		}
	},
	"os": {
		"loadavg": [0.25927734375,
		0.23046875,
		0.18798828125],
		"uptime": 548897
	},
	"trace": [{
		"column": 41,
		"file": "/var/www/node/shop_radiotaxivenezia/node_modules/paypal-rest-sdk/lib/paypal-rest-sdk.js",
		"function": "",
		"line": 238,
		"method": null,
		"native": false
	},
	{
		"column": 20,
		"file": "events.js",
		"function": "emitNone",
		"line": 85,
		"method": null,
		"native": false
	},
	{
		"column": 7,
		"file": "events.js",
		"function": "IncomingMessage.emit",
		"line": 179,
		"method": "emit",
		"native": false
	},
	{
		"column": 12,
		"file": "_stream_readable.js",
		"function": "endReadableNT",
		"line": 913,
		"method": null,
		"native": false
	},
	{
		"column": 13,
		"file": "node.js",
		"function": "_combinedTickCallback",
		"line": 377,
		"method": null,
		"native": false
	},
	{
		"column": 11,
		"file": "node.js",
		"function": "process._tickCallback",
		"line": 401,
		"method": "_tickCallback",
		"native": false
	}],
	"stack": ["TypeError: Cannot assign to read only property 'httpStatusCode' of {\"scope\":\"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://api.paypal.com/v1/vault/credit-card/.*\",\"nonce\":\"2016-04-05T18:56:12Z3kO4n1cF9lDaJ5WbTpiL5q9l9W587j-FFaU7CzbIYxg\",\"access_token\":\"*********************\",\"token_type\":\"Bearer\",\"app_id\":\"*********************\",\"expires_in\":32400}",
	"    at IncomingMessage.<anonymous> (/var/www/node/shop_radiotaxivenezia/node_modules/paypal-rest-sdk/lib/paypal-rest-sdk.js:238:41)",
	"    at emitNone (events.js:85:20)",
	"    at IncomingMessage.emit (events.js:179:7)",
	"    at endReadableNT (_stream_readable.js:913:12)",
	"    at _combinedTickCallback (node.js:377:13)",
	"    at process._tickCallback (node.js:401:11)"],
	"level": "error",
	"message": "uncaughtException: Cannot assign to read only property 'httpStatusCode' of {\"scope\":\"https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/payments/.* https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/applications/webhooks openid https://api.paypal.com/v1/vault/credit-card/.*\",\"nonce\":\"2016-04-05T18:56:12Z3kO4n1cF9lDaJ5WbTpiL5q9l9W587j-FFaU7CzbIYxg\",\"access_token\":\"*********************\",\"token_type\":\"Bearer\",\"app_id\":\"***********************\",\"expires_in\":32400}",
	"timestamp": "2016-04-05T18:56:11.593Z"
}
```

Thanks for help

**Comment by ppmtscory** [comment] 2016-06-29 20:15
Do you have any way to reliably recreate this scenario?

**Comment by gharlock** [comment] 2016-06-30 07:33
Unfortunately not. All my attempts were successful both in sandbox and in production.

**Comment by ppmtscory** [comment] 2016-06-30 14:38
Hmm.. I wonder if it was just a system glitch at the time.  Perhaps one of our internal services were being updated or you ran into a bad box.  I'm going to close this out as we're unable to reproduce, but please do re-open or file a new issue if you see it happen again.

**Closed by ppmtscory** 2016-06-30 14:38 UTC
Labels: question
