### ISSUE TITLE
Payout error: THIRD_PARTY_CALLS_FORBIDDEN

### ISSUE THREAD

**Issue by thiennq** [paypal/PayPal-node-SDK#101] opened 2015-07-14 11:06 UTC
Hi, 
I create an payout request in sandbox mode and receive this response:

{
  "response": {
    "name": "THIRD_PARTY_CALLS_FORBIDDEN",
    "message":"An internal service error has occurred.",
     "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#THIRD_PARTY_CALLS_FORBIDDEN",
    "httpStatusCode":403
  },
  "httpStatusCode":403
}

**Comment by avidas** [comment] 2015-07-14 12:37
Can you share more details about the specific call that you were making? Is it a single/batch payout, did you try it in synchronous or aysnc mode?

**Comment by thiennq** [comment] 2015-07-14 16:11
I'm using ES7 with babel, here my payout wrapper function
```javascript
async function payout(option) {
    try {
        var recipient_email = option.recipient_email;
        var sender_batch_id = Math.random().toString(36).substring(9);
        var transaction_id = option.transaction_id;
        var amount = option.amount;
        var create_payout_json = {
            "sender_batch_header": {
                "sender_batch_id": sender_batch_id,
                "email_subject": "MyApp Report"
            },
            "items": [
                {
                    "recipient_type": "EMAIL",
                    "amount": {
                        "value": numberToString(amount),
                        "currency": "USD"
                    },
                    "receiver": recipient_email,
                    "note": "Thanks for using MyApp",
                    "sender_item_id": "myapp"
                }
            ]
        };



        var sync_mode = 'true';
        var promise = new Promise(function(resolve, reject) {
            paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
                if (error) {
                    return resolve(error);
                } else {
                    return resolve(payout);
                }
            });
        });
        var result = await promise;
        if (!result.httpStatusCode) {
            return false;
        }
        // httpStatusCode != 2xx
        if (Math.floor(result.httpStatusCode/100) !== 2) {
            return false;
        }
        return result;
    }
    catch (e) {
        return false;
    }
}
```

The problem is when I write a testcase which include paypal module (which contains payout function) and run it, the result is OK.

But when I include paypal module to my app, using it to make some future payments then payout, the payout action will return THIRD_PARTY_CALLS_FORBIDDEN error.

**Comment by thiennq** [comment] 2015-07-14 16:12
Can previous actions effect to paypal module and create that error?

**Comment by avidas** [comment] 2015-07-15 14:44
For narrowing down the issue, it could be be worth trying to see if that issue is replicable in a script .e.g. do a future payment and then try to do a payout and see if the same issue comes up?

**Comment by avidas** [comment] 2015-07-15 14:50
It would be also useful if you could provide the [debug_id](https://github.com/paypal/PayPal-node-SDK#debugging) from your when you are running into the THIRD_PARTY_CALLS_FORBIDDEN issue.

**Comment by avidas** [comment] 2015-08-13 14:10
Closing, reopen if the issue is still happening.

**Closed by avidas** 2015-08-13 14:10 UTC
Labels: api-payouts, question
