### ISSUE TITLE
Payment Approval step fails when return_url  includes  "localhost" 

### ISSUE THREAD

**Issue by RozzyNoder** [paypal/PayPal-node-SDK#103] opened 2015-08-11 16:24 UTC
In the  three step process of accepting Paypal Payment, the  user approval is step 2 where the REST API redirects user  to the merchant specified return_url. But by specifying localhost or variation thereof  in  "create_payment_json" object causes the failure of  the redirection. Thus the next step of Payment Execution can't be executed.
........
"redirect_urls": {
	        "return_url": "http://localhost:5050/rest/payments/ep.js?success=true",
	        "cancel_url": "http://localhost.5050/test/rest/payments/ep.js?success=false"
	    },
......

This is a common occurrence both in corporate as well as individual work setup for sandbox testing so  this should work. The alternatives from both network admin, firewall  as well getting public server for preproduction  code are way too  cumbersome.

So please make this work or provide an easy alternative to get around this shortcoming.

**Comment by avidas** [comment] 2015-08-12 14:50
Is there a particular error message that you are getting? I tried creating some sandbox payments with return and cancel url set to localhost and redirection seem to be working fine.

**Comment by RozzyNoder** [comment] 2015-08-12 15:39
After I authorize the payment it attempts to redirect which I can see in the address bar but then it returns back to the same Paypal authorization page as the redirection fails. I tried putting IPs a 127.. and 198... and so on but the redirection still fails.

 When I put the actual ip of my router I get "The requested URL ........... was not found on the RomPager server". But the URL in my browser is properly encoded with PaymentID, PayerID and Token. 

The issue was mentioned in other forums too so I am not the only one with the problem.

**Comment by avidas** [comment] 2015-08-13 14:06
Hey just to sanity check, you have the redirect url set here right? 
![redirect_uri](https://cloud.githubusercontent.com/assets/873597/9251788/7bd94eb2-419a-11e5-8ff5-9158512851f1.jpg)

**Comment by ppmtscory** [comment] 2015-08-13 15:58
@RozzyNoder I'm wondering if everything is set up correctly with your localhost as I'm not able to reproduce your issue.  When I run the sample code from the SDK, I'm setting my return URL to http://localhost:5050/execute and I'm being redirected just fine.  All I do on that URL is print out the query parameters but everything with the redirect works like it should.  Can you check that there's not a random redirect in your code that's causing it to loop back to the PayPal page instead of your localhost page?

The only way I'm able to reproduce your issue is if I specify an invalid port for localhost (5000 instead of 5050).  When I do that, then I get a webpage not found error but with all the proper query params attached in the URL.

**Comment by RozzyNoder** [comment] 2015-08-13 18:31
I set the sandbox return url setting to localhost after Avi mentioned it but that has not made any difference so far. Perhaps it takes longer to get set. 

As far as random redirect in my code I am just doing the create payment call that is it. Only place I specify the redirect url is JSON structure. Let me try after few more hours hopefully  it might make a difference.

**Comment by RozzyNoder** [comment] 2015-08-14 10:41
@ppmtscory I tried again but does not work. Also tried using a HTTP header capture but interesting stuff happens on Paypal server. Is there a way for me too look at the app error from the PayPal network perspective when the redirect occurs and then fails ? Thx

**Comment by ppmtscory** [comment] 2015-08-14 14:19
@RozzyNoder I'm curious if you use 'inspect element' within Chrome, what is the HTTP response code that your site is giving?  Also, are you able to navigate to your localhost just via web instead of the PayPal redirect?  

Since this isn't an issue with the SDK itself, if you need any further assistance, we may need to have you work with our [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask/) team.

**Comment by avidas** [comment] 2015-08-19 15:13
Closing as per ^^

**Closed by avidas** 2015-08-19 15:13 UTC
