### ISSUE TITLE
Issues with returning multiple payments with paypal.payment.list()

### ISSUE THREAD

**Issue by dadsquatch** [paypal/PayPal-node-SDK#362] opened 2018-04-24 16:52 UTC
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: Not available
* Language, language version, and OS: Running locally through Node 6.11.3 and Express 4.16.3 

### Issue description
When using paypay.payment.list only a single result is being returned versus the default 10 or specified amount. Have 7 or 8 recent transactions placed in my sandbox account, but only displays the last one. 

```exports.listRecentOrders = (req, res) => {
  const listOptions = {
    count: '10',
    start_index: '1'
  }
  paypal.payment.list(listOptions,(error, payment) => {
    if(error){
      console.log(error)
    } else {
      console.log(payment.payments.length);
      res.status(200).send(payment.payments);
    }
  })
}```

Count always returns 1 no matter the adjustments to listOptions.

**Comment by xiaoleih41** [comment] 2018-04-24 17:06
what date range did you set?

**Comment by dadsquatch** [comment] 2018-04-24 17:08
I do not have these set anywhere. Are these required in the object? 

The examples in both SDK and on docs don't show it.

**Comment by xiaoleih41** [comment] 2018-04-24 17:34
Change `start_index` to `0`. Can you get any? I am not able to reproduce your issue.

**Comment by dadsquatch** [comment] 2018-04-24 17:39
```exports.listRecentOrders = (req, res) => {
  var listPayment = {
    'count': '10',
    'start_index': '0'
  };

  paypal.payment.list(listPayment, function (error, payments) {
      if (error) {
          throw error;
      } else {
          console.log("List Payments Response");
          console.log(JSON.stringify(payments));
          res.send(payments);
      }
  });```

The following returns this as payments:

![image](https://user-images.githubusercontent.com/19417626/39204116-dedbc976-47c4-11e8-8caf-3406059f0798.png)

Here is the sandbox account overview that it's linked to.

![image](https://user-images.githubusercontent.com/19417626/39204074-b45b54d2-47c4-11e8-95f7-872cb7af74ab.png)
 
// All payments in blurred column are completed status.

**Comment by dadsquatch** [comment] 2018-04-25 12:17
@xiaoleih41 go ahead and close this as it looks like you fixed the card processing issue. I'll report back if I see anything else, now that this is working, the same code from yesterday is working today flawlessly.

**Comment by xiaoleih41** [comment] 2018-04-27 16:27
Close the issue per the user's request.

**Closed by xiaoleih41** 2018-04-27 16:27 UTC
