### ISSUE TITLE
handling_fee disappearing on live

### ISSUE THREAD

**Issue by nicknasirpour** [paypal/PayPal-node-SDK#113] opened 2015-10-09 10:46 UTC
Hi, I'm selling a product that has both tax and a handling fee. It works perfectly fine in sandbox mode, but when I swap credentials over to live, the handling_fee disappears from the details in transactions-> amount.details. The tax stays, however. This throws the following error when I try to execute the payment: 

{ name: 'VALIDATION_ERROR',
  details: 
   [ { field: 'transactions[0].amount',
       issue: 'Transaction amount details (subtotal, tax, shipping) must add up to specified amount total' } ],
  message: 'Invalid request - see details',
  information_link: 'https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR',
  debug_id: '87d8a3098676b',
  httpStatusCode: 400 }

Here's my debug-id: paypal-debug-id: 87d8a3098676b

**Comment by avidas** [comment] 2015-10-09 15:05
Hey, @nicknasirpour thanks for providing the debug-id, we will take a look and get back to you soon.

**Comment by avidas** [comment] 2015-10-09 16:09
@nicknasirpour can you post the full request you were making as well so that we can try it out? (Please don't provide any sensitive information such as client_id/secret, card information)

**Comment by nicknasirpour** [comment] 2015-10-09 16:37
Sure, I create my payment with this json:
{
      "intent": "authorize",
      "payer": {
        "payment_method": "paypal"
      },
      "redirect_urls": {
        "return_url": returnurl,
        "cancel_url": canceler'
      },
      "transactions": [{
        "item_list": {
          "items": [{
            "name": name,
            "sku": "earlypc",
            "price": "20.00",
            "currency": "CAD",
            "quantity": 1
          }]
        },
        "amount": {
          "currency": "CAD",
          "total": "20.90",
          "details": {
            "subtotal": "20.00",
            "tax": "0.60",
            "handling_fee": "0.30"
          }
        },
        "description": "description"
      }]
    };

Then paypal returns to another route which gets the payment and executes using: 
{
          "payer_id": req.query.PayerID,
          "transactions": [{
            "amount": {
              "total": payment.transactions[0].amount.total,
              "currency": payment.transactions[0].amount.currency,
              "details": {
                "subtotal": payment.transactions[0].amount.details.subtotal,
                "tax": payment.transactions[0].amount.details.tax,
                "handling_fee": payment.transactions[0].amount.details.handling_fee
              }
            }
          }]
        }

It took me a while to realize what happened, but it seems the handling_fee just disappears when I'm running with my live credentials. I tried changing it to simply "handling" with no luck, seeing as "shipping" works. But the fee I'm using isn't a shipping fee, so I'd prefer to use handling for aesthetic purposes.

**Comment by avidas** [comment] 2015-10-12 15:33
Hey @nicknasirpour , I just tested on live and sandbox and unable to reproduce the issue at this moment. Are you still seeing the same issue?

**Comment by avidas** [comment] 2015-10-19 18:43
closing as cannot reproduce, reopen if the issue still exists.

**Closed by avidas** 2015-10-19 18:43 UTC
Labels: question
