### ISSUE TITLE
Single Payout on sync_mode='false' always pending

### ISSUE THREAD

**Issue by madsithlord** [paypal/PayPal-node-SDK#264] opened 2017-04-25 10:12 UTC
* SDK/Library version: Example: 6.5.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 821215d375cf2, 821215d375cf2 
* Language, language version, and OS:  Ubuntu 14.04.5 LTS

### Issue description
I am trying to implement single payout on my node app. As I can see, PayPal recommend to use sync_mode='false' as sync_mode is going to be deprecated. I followed the example but it didn't send money to the user when I use sync_mode='false'.

I figured that I have to use payout.get() method to do further actions and I did that too. Now Users can receive payments. However, `batch_status: 'PENDING'` always pending but if I try sync_mode='true' then I get SUCCESS.

Am I missing something here? I couldn't find any reliable example to use async mode. 

Here is the code that I have used,

```
   // paypal payment configuration.
  var sender_batch_id = Math.random().toString(36).substring(9);
  console.log('random batch id', sender_batch_id);
  var create_payout_json = {
      "sender_batch_header": {
          "sender_batch_id": sender_batch_id,
          "email_subject": "You have a payment"
      },
      "items": [
          {
              "recipient_type": "EMAIL",
              "amount": {
                  "value": 0.90,
                  "currency": "USD"
              },
              "receiver": "redhoodcool@gmail.com",
              "note": "Thank you.",
              "sender_item_id": "item_3"
          }
      ]
  };
 
  var sync_mode = 'false';

  paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
      if (error) {
          console.log(error.response);
          throw error;
      } else {
          console.log("Create Single Payout Response");
          console.log(payout);
          var payoutId = payout.batch_header.payout_batch_id;
          paypal.payout.get(payoutId, function (error, payout) {
              if (error) {
                  console.log(error);
                  throw error;
              } else {
                  console.log("Get Payout Response");
                  console.log(JSON.stringify(payout));
              }
          });
      }
  }); 

```

Here is the response that I have got,

```
{
  "batch_header": {
    "payout_batch_id": "EHW5NSANEKJHG",
    "batch_status": "PENDING",
    "time_created": "2017-04-25T09:20:20Z",
    "sender_batch_header": {
      "email_subject": "You have a payment",
      "sender_batch_id": "vbbwwhjuke3o9a4i"
    },
    "amount": {
      "currency": "USD",
      "value": "0.9"
    },
    "fees": {
      "currency": "USD",
      "value": "0.25"
    }
  },
  "items": [
    {
      "payout_item_id": "46YBT5R2DGM2S",
      "transaction_status": "PENDING",
      "payout_item_fee": {
        "currency": "USD",
        "value": "0.25"
      },
      "payout_batch_id": "EHW5NSANEKJHG",
      "payout_item": {
        "amount": {
          "currency": "USD",
          "value": "0.9"
        },
        "note": "Thank you.",
        "receiver": "redhoodcool@gmail.com",
        "recipient_type": "EMAIL",
        "sender_item_id": "item_3"
      },
      "links": [
        {
          "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts-item\/46YBT5R2DGM2S",
          "rel": "item",
          "method": "GET"
        }
      ]
    }
  ],
  "links": [
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts\/EHW5NSANEKJHG",
      "rel": "self",
      "method": "GET"
    }
  ],
  "httpStatusCode": 200
}
```

**Comment by pp-randy** [comment] 2017-04-25 14:31
I am seeing completed payments to your receiver account.  Is this one still showing as pending?  Also have you considered using [Webhooks](https://developer.paypal.com/docs/api/webhooks/) so you are notified when a payout completes or fails?

**Comment by xiaoleih41** [comment] 2017-04-25 14:44
@madsithlord  This actually is expected behavior for payouts in **async** mode. The payment will be sent to a queue first then be executed so it will show pending in the immediate response but it will be processed in a later time. Based on the transaction log, it looks like the delay was a second or two for your transactions.

**Comment by madsithlord** [comment] 2017-04-25 15:33
@pp-randy Yes, I have waited for sometime(like an hour or so), it was still pending but of course the payment went through immediately. That's why I raised this issue to get some help. I haven't tried the webhooks yet but I can look into it. 

It would be awesome to have the async mode on payout sample instead of the old one. 

@xiaoleih41 I understand but shouldn't it update to successful when the payment went through? It's always pending even though the payment went through. That's why I wanted to make sure I am doing it correctly. Also, I couldn't find any samples for async mode

**Comment by pp-randy** [comment] 2017-04-25 16:00
When you [`get`](https://github.com/paypal/PayPal-node-SDK/blob/master/samples/payout/get.js) a payout it should have the current status and the payout_items, if its completing correctly.
`{"batch_header":{"payout_batch_id":"TMTTDUKXTBCHW","batch_status":"SUCCESS",`

Can you provide the debug_id from the `get` call for `EHW5NSANEKJHG` and I look into the logging to see what I can find out? 

Thank you for letting us know about the samples I will review those as well, we do appreciate pull requests as well 👍.

**Comment by pp-randy** [comment] 2017-04-25 16:07
Also... Awesome GitHub username @madsithlord...

**Comment by madsithlord** [comment] 2017-04-26 09:22
@pp-randy, I did another testing and I got the same result and copying the responses from request here. I have got three different Paypal debug id. I am copying all of them here.

paypal-debug-id: 714d4c577c708, 714d4c577c708

```
{
  "sender_batch_header": {
    "sender_batch_id": "ouo72bhe05ujqyqfr",
    "email_subject": "You have a payment"
  },
  "items": [
    {
      "recipient_type": "EMAIL",
      "amount": {
        "value": 0.9,
        "currency": "USD"
      },
      "receiver": "redhoodcool@gmail.com",
      "note": "Thank you.",
      "sender_item_id": "item_3"
    }
  ]
}
```
========================================================================

paypal-debug-id: 8509c15112d42, 8509c15112d42

```
{
  "batch_header": {
    "payout_batch_id": "WUXRN6B7MNY46",
    "batch_status": "PENDING",
    "sender_batch_header": {
      "email_subject": "You have a payment",
      "sender_batch_id": "ouo72bhe05ujqyqfr"
    }
  },
  "links": [
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts\/WUXRN6B7MNY46",
      "rel": "self",
      "method": "GET"
    }
  ]
}
```

========================================================================

paypal-debug-id: 28a3375392eac, 28a3375392eac

```
{
  "batch_header": {
    "payout_batch_id": "WUXRN6B7MNY46",
    "batch_status": "PENDING",
    "time_created": "2017-04-26T08:59:50Z",
    "sender_batch_header": {
      "email_subject": "You have a payment",
      "sender_batch_id": "ouo72bhe05ujqyqfr"
    },
    "amount": {
      "currency": "USD",
      "value": "0.9"
    },
    "fees": {
      "currency": "USD",
      "value": "0.25"
    }
  },
  "items": [
    {
      "payout_item_id": "C8QK9XH2P5VK6",
      "transaction_status": "PENDING",
      "payout_item_fee": {
        "currency": "USD",
        "value": "0.25"
      },
      "payout_batch_id": "WUXRN6B7MNY46",
      "payout_item": {
        "amount": {
          "currency": "USD",
          "value": "0.9"
        },
        "note": "Thank you.",
        "receiver": "redhoodcool@gmail.com",
        "recipient_type": "EMAIL",
        "sender_item_id": "item_3"
      },
      "links": [
        {
          "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts-item\/C8QK9XH2P5VK6",
          "rel": "item",
          "method": "GET"
        }
      ]
    }
  ],
  "links": [
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts\/WUXRN6B7MNY46",
      "rel": "self",
      "method": "GET"
    }
  ],
  "httpStatusCode": 200
}
```

**Comment by madsithlord** [comment] 2017-04-26 09:24
@pp-randy, Big fan of Star wars :)

**Comment by pp-randy** [comment] 2017-04-26 13:46
These API calls are seconds apart and most likely the payout batch was not completed in that time, 'PENDING' could still be expected.  

What does the 'GET' for this exact same payout batch 'WUXRN6B7MNY46' showing you now?

**Comment by sudharsan1988** [comment] 2017-04-26 16:10
@pp-randy Yes, here is the response for WUXRN6B7MNY46

But it looks like, we have to wait for it even for single payout. Is there any other way to get this status immediately like sync_mode='true'. Only way is to use web hooks?

```
{
  "batch_header": {
    "payout_batch_id": "WUXRN6B7MNY46",
    "batch_status": "SUCCESS",
    "time_created": "2017-04-26T08:59:50Z",
    "time_completed": "2017-04-26T09:00:13Z",
    "sender_batch_header": {
      "email_subject": "You have a payment",
      "sender_batch_id": "ouo72bhe05ujqyqfr"
    },
    "amount": {
      "currency": "USD",
      "value": "0.9"
    },
    "fees": {
      "currency": "USD",
      "value": "0.25"
    }
  },
  "items": [
    {
      "payout_item_id": "C8QK9XH2P5VK6",
      "transaction_id": "82K62420T6729135N",
      "transaction_status": "SUCCESS",
      "payout_item_fee": {
        "currency": "USD",
        "value": "0.25"
      },
      "payout_batch_id": "WUXRN6B7MNY46",
      "payout_item": {
        "amount": {
          "currency": "USD",
          "value": "0.9"
        },
        "note": "Thank you.",
        "receiver": "redhoodcool@gmail.com",
        "recipient_type": "EMAIL",
        "sender_item_id": "item_3"
      },
      "time_processed": "2017-04-26T09:00:06Z",
      "links": [
        {
          "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts-item\/C8QK9XH2P5VK6",
          "rel": "item",
          "method": "GET"
        }
      ]
    }
  ],
  "links": [
    {
      "href": "https:\/\/api.sandbox.paypal.com\/v1\/payments\/payouts\/WUXRN6B7MNY46",
      "rel": "self",
      "method": "GET"
    }
  ],
  "httpStatusCode": 200
}
```

**Comment by madsithlord** [comment] 2017-04-26 16:31
@pp-randy Sorry, just realised. I posted my comment with my other account :)

**Comment by pp-randy** [comment] 2017-04-26 17:50
It won't be immediate, but a webhook would be sent to you at least to let you know when a payout_item completed.  A webhook seems a better option than needing to pull manually every so often.   If you have a web server, then I would encourage you check them out. 

Unfortunately, I'm not aware of an alternative with the REST API to sync_mode='true'.

**Comment by madsithlord** [comment] 2017-04-26 19:22
@pp-randy, Sure, I will look into the Webhooks. Thank you for help. I really appreciate it :)

**Comment by xiaoleih41** [comment] 2017-05-05 14:34
Close this issue as it appears that it might have been resolved. Please let us know if you have any further questions.

**Closed by xiaoleih41** 2017-05-05 14:34 UTC
Labels: question, sdk-enhancement
