### ISSUE TITLE
Paypal sandbox payout 403 Authorisation error 

### ISSUE THREAD

**Issue by rihbyne** [paypal/PayPal-node-SDK#249] opened 2017-03-07 06:18 UTC
Hi there,
I have tried REST API as well as the NodeJS SDK in sandbox.
When I use the batch payout API like this -

`curl -X POST -H "Content-Type: application/json" 
                       -H "Authorization: Bearer A101.eD3BRlf3IY5zH8op5b7Rhq6IL3SQDmvHlDfTmdWi2CezZBcTpCCC-RY7EQ0nX08.zfmPebaEKqWH0AYy4F5Q_fRBCUG" 
                       -H "Accept: application/json" -H "Cache-Control: no-cache"  
                       -d '{
	                       "sender_batch_header": {
		               "sender_batch_id":"1",
                               "email_subject": "You have a payout!"
                                },
                               "items": [
                                           {
                                                "recipient_type": "EMAIL",
                                                "amount": {
                                                    "value": "9.87",
                                                    "currency": "USD"
                                                 },
                                                "note": "Thanks for your patronage!",
                                                "sender_item_id": "A1",
                                                "receiver": "cashdummy@gmail.com"
                                           }
                                  ]
                            }' "https://api.sandbox.paypal.com/v1/payments/payouts"`

Obviously, in both cases I get -
`{
  "name": "AUTHORIZATION_ERROR",
  "message": "Authorization error occurred",
  "debug_id": "423c15157995f",
  "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"
}`

How should it work ?

**Comment by pp-randy** [comment] 2017-03-07 14:40
Do you have Payouts enabled on your REST application?

![image](https://cloud.githubusercontent.com/assets/6819909/23661229/b65fa4fc-0311-11e7-8672-17f0fa97ee7e.png)

**Comment by rihbyne** [comment] 2017-03-08 07:20
@pp-randy  Yes I did have it enabled. Why is mass payout not working out in 'sandbox' mode? If its live then its a different question. How should I make it work other wise ? Any hack?

**Comment by pp-randy** [comment] 2017-03-08 22:11
Just to rule out a credential issue. Do your credentials work for a payment? 

You could try testing with a US account since I think payouts are on by default.   I'm looking to see what it will take for an Indian based account.

**Comment by pp-randy** [comment] 2017-03-08 22:12
On that note, it wouldn't hurt to find out from PayPal Customer Support if Payouts are supported in India I'm not 100% sure but believe they are https://www.paypal.com/selfhelp/home

**Comment by pp-randy** [comment] 2017-03-10 14:47
@rihbyne did you follow up with support?  I don't think Payouts are supported in India on live which would explain this not working in the sandbox.  I reproduced this issue in sandbox, so I know it isn't a code issue.

**Comment by pp-randy** [comment] 2017-03-10 14:56
Closing the issue for now, please let me know if you find out more.

**Closed by pp-randy** 2017-03-10 14:56 UTC
Labels: question

**Comment by apandey14** [comment] 2017-12-01 10:33
Hello ,

I have write the code and call in our app.js file but I am getting this issue all time. Please check and let me know how to solved it





var connection = require('./../dbconnection');
var express = require('express');
var paypal = require('paypal-rest-sdk');

var router = express.Router();
 router.testpaypal=function(req,res){
    paypal.configure({
        'mode': 'sandbox', //sandbox or live
        'client_id': '*******************************',
        'client_secret': '******************************'
      });
        var UserId=req.body.UserId;
        var RedeemPoint=req.body.RedeemPoint;
        connection.query("SELECT * FROM users WHERE id = '"+UserId+"' ORDER BY id LIMIT 1", function (error, results, fields) {
        if (error) 
        {
        console.log(error);
        res.json("fail internal error"+"\r\n");
        }  
        console.log('fail');
        // res.json("fail user already exists");  
        if (results.length  > 0) {

         

  var sender_batch_id = Math.random().toString(36).substring(9);
  var EmailId = results[0].EmailId;
  var Mobile = results[0].Mobile;
  var create_payout_json = {
      "sender_batch_header": {
          "sender_batch_id": sender_batch_id,
          "email_subject": "You have a payment"
      },
      "items": [
          {
              "recipient_type": "EMAIL",
              "amount": {
                  "value": RedeemPoint,
                  "currency": "USD"
              },
              "receiver": EmailId,
              "note": "Thank you.",
              "sender_item_id": "item_1"
          }

      ]
  };
  
  var sync_mode = 'true';
  
  paypal.payout.create(create_payout_json, sync_mode, function (error, payout) {
      if (error) {
          console.log(error.response);
          throw error;
      } else {
          console.log("Create Single Payout Response");
          console.log(payout);
      }
  });
  
  res.json({
    "available": "yes", 
    message: "Your point has been redeem successfully! It will update shortly in paypal",
    batchid:sender_batch_id
    })
}else{
    res.json({
        "available": "no", 
        message: "Sorry!Your payment has been decline"
        })

};

});
 }
module.exports=router;



![image](https://user-images.githubusercontent.com/27541600/33478908-ece952ac-d6b0-11e7-97b1-1ec3bbc18b70.png)

![image](https://user-images.githubusercontent.com/27541600/33478932-0eb7a564-d6b1-11e7-9362-3da0e9bde183.png)

**Comment by xiaoleih41** [comment] 2017-12-04 20:22
Indian account doesn't support payout API. Please open a US account then create app to try again.

**Comment by parths049** [comment] 2017-12-14 13:55
Hi All,

I am getting same issue.

https://stackoverflow.com/questions/47807904/paypal-masspayout-getting-403-error

**Comment by xiaoleih41** [comment] 2017-12-19 21:03
Looks like the issue has been solved for you.

**Comment by NazmusShakib** [comment] 2019-05-14 23:44
Sandbox is working properly but when I turn to live it shows - Got Http response code 403 when accessing https://api.paypal.com/v1/payments/payouts?.

Is there any solution for PayPal payout service?
