### ISSUE TITLE
Web-hook API Issues

### ISSUE THREAD

**Issue by night** [paypal/PayPal-node-SDK#68] opened 2015-02-11 19:18 UTC
When retrieving a list of web-hook events, the resource links point to intranet URLs:

```
            "links": [{
                "href": "https://10.74.133.169:17881/v1/payments/sale/:transactionId",
                "rel": "self",
                "method": "GET"
            }, {
                "href": "https://10.74.133.169:17881/v1/payments/sale/:transactionId/refund",
                "rel": "refund",
                "method": "POST"
            }, {
                "href": "https://10.74.133.169:17881/v1/payments/payment/:payId",
                "rel": "parent_payment",
                "method": "GET"
            }],
```

Additionally, I have been unable to resend a web-hook event. I get the following error when I try:

```
exception

java.lang.RuntimeException: org.apache.cxf.interceptor.Fault
	org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:117)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:331)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:239)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:203)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:137)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:158)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:243)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:163)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:219)
	com.paypal.foundation.service.rest.logging.StandardOuterTransactionCALFilter.doFilter(StandardOuterTransactionCALFilter.java:94)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.paypal.common.resource.filter.SecurityContextFilter.doFilter(SecurityContextFilter.java:75)
	
root cause

org.apache.cxf.interceptor.Fault
	org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:194)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:102)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:239)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:203)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:137)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:158)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:243)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:163)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:219)
	com.paypal.foundation.service.rest.logging.StandardOuterTransactionCALFilter.doFilter(StandardOuterTransactionCALFilter.java:94)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.paypal.common.resource.filter.SecurityContextFilter.doFilter(SecurityContextFilter.java:75)
	
root cause

java.lang.ExceptionInInitializerError
	com.paypal.webhooks.bl.notification.NotificationFinderImpl.findEventByEventId(NotificationFinderImpl.java:43)
	com.paypal.webhooks.handler.WebhooksEventsHandler.handleResendNotification(WebhooksEventsHandler.java:177)
	com.paypal.webhooks.WebhooksEventsImpl.resendNotification(WebhooksEventsImpl.java:73)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:194)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:102)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:239)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:203)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:137)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:158)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:243)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:163)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:219)
	com.paypal.foundation.service.rest.logging.StandardOuterTransactionCALFilter.doFilter(StandardOuterTransactionCALFilter.java:94)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.paypal.common.resource.filter.SecurityContextFilter.doFilter(SecurityContextFilter.java:75)
	
root cause

java.lang.IllegalArgumentException: encrypted_webhook_event_id_mac_key not specified in protected properties file
	com.paypal.foundation.security.crypto.AbstractIdEncryptor.getProtectedProperty(AbstractIdEncryptor.java:121)
	com.paypal.foundation.security.crypto.ObjectIdEncryptor.getEncryptor(ObjectIdEncryptor.java:37)
	com.paypal.foundation.security.crypto.AbstractIdEncryptor.initialize(AbstractIdEncryptor.java:95)
	com.paypal.webhooks.clients.util.WebhookEventIdCryptUtils.<init>(WebhookEventIdCryptUtils.java:32)
	com.paypal.webhooks.clients.util.WebhookEventIdCryptUtils.<clinit>(WebhookEventIdCryptUtils.java:20)
	com.paypal.webhooks.bl.notification.NotificationFinderImpl.findEventByEventId(NotificationFinderImpl.java:43)
	com.paypal.webhooks.handler.WebhooksEventsHandler.handleResendNotification(WebhooksEventsHandler.java:177)
	com.paypal.webhooks.WebhooksEventsImpl.resendNotification(WebhooksEventsImpl.java:73)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:194)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:102)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:271)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:239)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:223)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:203)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:137)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:158)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:243)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:163)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:219)
	com.paypal.foundation.service.rest.logging.StandardOuterTransactionCALFilter.doFilter(StandardOuterTransactionCALFilter.java:94)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	com.paypal.common.resource.filter.SecurityContextFilter.doFilter(SecurityContextFilter.java:75)
	
```

And lastly, eChecks appear to not send web-hook events upon completion (despite your documentation stating that they do). I have, however, gotten some web-hook events for non-eCheck payments.

From https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/
> PAYMENT.SALE.COMPLETED: This event gets triggered when the sale is completed for eCheck.

**Comment by avidas** [comment] 2015-02-11 19:27
Is this happening on both sandbox and the live environment?

**Comment by night** [comment] 2015-02-11 19:41
I have not been able to test web-hooks properly on the sandbox environment as there's not a way to send eCheck payments. Refunding a sent payment also seems to not trigger a web-hook on sandbox either.

**Comment by avidas** [comment] 2015-02-13 15:36
Hey @night I have found out that there is active work going on to fix the intranet URL issue and we will keep you updated here. We will try to get you more feedback on the remaining issues as well.

**Comment by avidas** [comment] 2015-02-26 15:24
@night  The resend issue should be fixed now and the intranet URL issue fix is going to go out soon.

**Comment by avidas** [comment] 2015-03-02 16:29
@night Intranet issue should be resolved now.

**Comment by night** [comment] 2015-03-10 00:19
Now that just leaves the last issue I listed: (most) cleared eChecks do not trigger a webhook event.

Example PAY-IDs (from production) that completed, and had no webhook: PAY-39388053R70580154KTZWKFA, PAY-6DJ55021Y38754147KT2GIYA, PAY-5P340398M05892613KT3VHIQ

**Comment by avidas** [comment] 2015-03-10 18:45
@night we will take a look at those ids and get back to you.

**Comment by night** [comment] 2015-04-03 18:05
@avidas Any updates on those PAY-IDs?

**Comment by avidas** [comment] 2015-04-03 18:15
Hey @night apologies for the delay, any chance you have some more recent PAY-IDs?

**Comment by night** [comment] 2015-04-03 18:18
The most recent I have is PAY-7CY03637G9904192TKUEIVAY, which cleared March 20 and sent no webhook call.

**Comment by avidas** [comment] 2015-04-03 18:24
Thanks @night do you have the Sale ID of that particular transaction? The sale id is returned in the response after you call [execute on the approved payment](https://developer.paypal.com/docs/api/#execute-an-approved-paypal-payment)

**Comment by night** [comment] 2015-04-03 18:25
@avidas That ID would be 2NP27880VW3103247

**Comment by avidas** [comment] 2015-04-06 14:37
@night We reached out to the API team responsible for web hooks. Will let you know when we get an update.

**Comment by night** [comment] 2015-04-08 22:03
Two more, in case it helps:

3GN12750AG949493N
5M199116C4918124Y

**Comment by night** [comment] 2015-04-13 17:38
I'm no longer receiving any web-hooks. I log all API payment calls and web-hooks, and the last web-hook I received was at 2015-04-06T09:08:31.281Z

**Comment by avidas** [comment] 2015-04-14 16:24
@night any Sale ID or [paypal debug ids](https://github.com/paypal/PayPal-node-SDK#debugging) you could provide?

**Comment by night** [comment] 2015-04-16 05:03
@avidas I was getting "completed" web-hooks for a lot of non-eCheck transactions (not all) after the payment was received, but those stopped completely (as my last reply dictated). It seems every transaction yields no web-hooks now.

Another pending transaction that completed without a web-hook (yesterday): 60555830Y71350233

At this point, it seems web-hooks are completely nonfunctional, which is an incredible nuisance. For a large payment provider, I would expect not to have this kind of issue when accepting payments (issues like this are okay in sandbox, but this is production).

Another bug: Here's the output of the web-hook event search API:

    {"events":[],"count":0,"httpStatusCode":200}

It doesn't seem to show any web-hooks, at least at first. About 5-10 minutes after, calling the API again gives you web-hooks you seek, but the last web-hook listed as sent is not the last I received. The reason for this is obvious, the internal request is timing out, but subsequent requests complete because the data is cached. The last web-hook I can get the API to spit back is anything before April 5th (specifically, the last I see is from "2015-04-04T23:59:22Z"). Anything past that point is unretrievable. Interestingly, I can still retrieve the missing web-hooks (from after April 4) by their event ID (since I log all web-hooks).

I'm also surprised I am the only one who has been encountering these issues. Perhaps I'm one of the few who are actually trying to use these web-hooks. I would prefer to use a REST interface with web-hooks than the Classic APIs with IPN, and it is sad that it is this unstable and unsuitable for production.

**Comment by alexkshu** [comment] 2015-04-16 22:42
Hi, this is Alex from PayPal webhooks team, sorry this issue happened to you. We're actively looking at your issue now. All the transaction ids you have shared seems are from echeck payment, to help us narrow down your problem, can you please run an instant payment through REST API, in the response header, you can find debug_id, please forward that id to us, that will help us trace your problem.

**Comment by night** [comment] 2015-04-17 07:52
Here is a debug_id from an INSTANT_TRANSFER payment: 01d152cc27f78

Unrelated: In the response from executing a sale, payer.payer_info.first_name is always "" (empty string). If you want, I can open another GitHub issue about that.

**Comment by jziaja** [comment] 2015-04-17 15:52
@night Please open another GitHub issue regarding the empty `first_name` and include the `debug_id` from the response header.  I wasn't able to reproduce that behavior on sandbox, so I'm not sure if it's related to the live service or something else.  Regardless, we'll notify the Payments API team of the issue.  Thanks!

**Comment by night** [comment] 2015-04-28 21:50
Any updates?

**Comment by alexkshu** [comment] 2015-04-28 22:48
Your problem has been identified, our engineer team is working on fixing your problem, will keep you posted after it gets fixed.

**Comment by xxxkilldogxxx** [comment] 2015-05-02 07:07
I really hope this gets fixed soon, cause the amount of support emails I am getting because of this is annoying now, and over the past couple weeks this has got worse and worse.

**Comment by xxxkilldogxxx** [comment] 2015-05-05 08:03
Could we please have a update one this, its getting very annoying.

**Comment by night** [comment] 2015-05-06 00:40
Any updates?

**Comment by avidas** [comment] 2015-05-06 01:18
Hey guys, really sorry about the delay here. This happened to be a broader issue than initially anticipated and there are multiple teams working on the fix at present. Because of the multiple moving pieces it is harder to put an exact date down but last I have heard they were planning on releasing in a week or two.

**Comment by xxxkilldogxxx** [comment] 2015-05-06 16:11
Okay well any update is better than no update I suppose, thank you @avidas  I am going to add my work around for the time being.

**Comment by night** [comment] 2015-05-12 21:43
Anymore updates?

**Comment by alexkshu** [comment] 2015-05-13 02:34
Can you try it now?

**Comment by xxxkilldogxxx** [comment] 2015-05-13 15:31
I am just making some changes to my code and once a payment comes through which wont take long ill response back with my findings.

**Comment by night** [comment] 2015-05-13 16:48
@alexkshu So I'm getting web-hooks now, but it appears that the requests are now malformed? My server is rejecting them with a 400 Bad Request because they don't appear to verify properly against their signature. Any idea why that might be? I'm using PayPal.notification.webhookEvent.verify from this repo, along with headers PAYPAL-CERT-URL, PAYPAL-TRANSMISSION-ID, PAYPAL-TRANSMISSION-TIME, PAYPAL-TRANSMISSION-SIG and the web-hook ID and raw body of the request.

**Comment by alexkshu** [comment] 2015-05-13 17:02
@night, signature validation test is passing on my side. Have you downloaded the latest certificate from CERT-URL? Can you use webhook-simulator to send an sample event to your url and see if it works?

**Comment by night** [comment] 2015-05-13 17:20
@alexkshu https://github.com/paypal/PayPal-node-SDK/blob/master/lib/resources/Notification.js#L48 The repo appears to grab it fresh on every IPN, so I'm not sure. The CERT-URL header is providing me with "https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-df8cd2d5" currently. I tried the simulator, but it just tells me "successfully queued" and I haven't gotten a POST from the server yet.

**Comment by night** [comment] 2015-05-13 18:07
Found the issue: https://github.com/paypal/PayPal-node-SDK/blob/master/lib/resources/Notification.js#L42

Auth-Alg is now SHA256withRSA

**Comment by alexkshu** [comment] 2015-05-13 18:41
please always get the algorithm from header instead of hard coding it.

**Comment by night** [comment] 2015-05-13 19:04
> please always get the algorithm from header instead of hard coding it.

Might want to suggest that to @avidas since that would require a change of the verify API in the SDK.

**Comment by avidas** [comment] 2015-05-13 19:10
@night we will update the SDK to start accepting the algorithm as a parameter

**Comment by night** [comment] 2015-05-14 00:25
@alexkshu So instant transfer payments come through properly, but not all eChecks do? This morning an eCheck transaction cleared, but I searched the web-hook events for today and did not see a web-hook generated for it (but I have an email confirming its' completion). The debug_id of the initial payment is 921d7072750fc. The transaction id is 11D24003RS694704H.

**Comment by alexkshu** [comment] 2015-05-14 17:11
@night, do you see this issue happening to all your echeck payment?

**Comment by night** [comment] 2015-05-14 17:22
@alexkshu Not all, but most eChecks appear to not generate a web-hook event. Maybe like 1 in 5 will, from what I've been seeing anyways.

**Comment by night** [comment] 2015-05-26 19:15
Any progress?

**Comment by usubhash** [comment] 2015-06-30 22:48
@night can you check now?

**Comment by night** [comment] 2015-07-09 23:00
@usubhash Sorry for the late response.

I got web-hooks for all eChecks since your reply except ```7LX37159S3120111F```. For this transaction, I received an email confirming the clearing at 6 Jul 2015 06:12:58 -0700 (PDT), but not a web-hook. I do not have the debug ID of the initial transaction, however, since I removed my logging of that.

**Comment by avidas** [comment] 2015-07-14 20:53
@night According to the API team this should be resolved now, please reopen if necessary.

**Closed by avidas** 2015-07-14 20:53 UTC
Labels: api-bug, api-webhooks, bug
