### ISSUE TITLE
500 error paypal.

### ISSUE THREAD

**Issue by NikitaKompanetc** [paypal/PayPal-node-SDK#314] opened 2017-11-02 10:07 UTC
hi guys, i try to send money from 1 person(admin) to many persons(sellers).
When i try to use
```
  paypal.payment.execute(req.query.paymentId, details, function(error, payment) {
            if (error) {
                console.log(error);
            } 
```
i get that json 
```
{
    "response": {
    "name": "INTERNAL_ERROR",
    "message": "An internal service error has occurred.",
    "debug_id": "445b89152a06d",
    "information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors",
    "httpStatusCode": 500
},
   "httpStatusCode": 500
 }
```
maybe some one know,whats is going wrong?

**Comment by xiaoleih41** [comment] 2017-11-03 19:28
It appears to be a PayPal issue. I am closing this issue and track it in https://github.com/paypal/PayPal-REST-API-issues/issues/165. Please follow the issue there for any updates.

**Closed by xiaoleih41** 2017-11-03 19:28 UTC

**Comment by kamalikasaha7** [comment] 2018-04-11 12:49
Again 500 error

**Comment by xiaoleih41** [comment] 2018-04-12 02:27
@kamalikasaha7 500 error can be caused by various reason. Please open a ticket with your debugID and detail steps for us to reproduce the error.
